// SPDX-License-Identifier: MIT
import { Mnemonic } from '../../mnemonic';
import { ElectrumV1Entropy, ELECTRUM_V1_ENTROPY_STRENGTHS } from '../../../entropies';
import { hexToBytes, integerToBytes, bytesToInteger, bytesToHex, getBytes, concatBytes } from '../../../utils';
import { MnemonicError, EntropyError } from '../../../exceptions';
import { ELECTRUM_V1_ENGLISH_WORDLIST } from './wordlists';
export const ELECTRUM_V1_MNEMONIC_WORDS = {
    TWELVE: 12,
};
export const ELECTRUM_V1_MNEMONIC_LANGUAGES = {
    ENGLISH: 'english'
};
/**
 * Electrum-V1 mnemonic implementation.
 *
 * Electrum-V1 mnemonics are generated by encoding entropy into
 * a sequence of words using the Electrum-V1 algorithm.
 */
export class ElectrumV1Mnemonic extends Mnemonic {
    static wordsListNumber = 1626;
    static wordsList = [
        ELECTRUM_V1_MNEMONIC_WORDS.TWELVE,
    ];
    static wordsToStrength = {
        [ELECTRUM_V1_MNEMONIC_WORDS.TWELVE]: ELECTRUM_V1_ENTROPY_STRENGTHS.ONE_HUNDRED_TWENTY_EIGHT,
    };
    static languages = Object.values(ELECTRUM_V1_MNEMONIC_LANGUAGES);
    static wordLists = {
        [ELECTRUM_V1_MNEMONIC_LANGUAGES.ENGLISH]: ELECTRUM_V1_ENGLISH_WORDLIST
    };
    /**
     * Get the name of this mnemonic type.
     *
     * @returns The string `"Electrum-V1"`.
     */
    static getName() {
        return 'Electrum-V1';
    }
    /**
     * Generate a mnemonic from word count and language.
     *
     * @param count - Number of words (must be in `wordsList`).
     * @param language - Language of the wordlist.
     * @param options - Optional mnemonic generation options.
     * @throws {MnemonicError} If the word count is invalid.
     * @returns A space-separated mnemonic string.
     */
    static fromWords(count, language, options = {}) {
        if (!this.wordsList.includes(count)) {
            throw new MnemonicError('Invalid mnemonic words number', { expected: this.wordsList, got: count });
        }
        const entropy = ElectrumV1Entropy.generate(this.wordsToStrength[count]);
        return this.encode(entropy, language, options);
    }
    /**
     * Generate a mnemonic from entropy.
     *
     * @param entropy - Entropy in hex string, Uint8Array, or Entropy object form.
     * @param language - Language of the wordlist.
     * @param options - Optional mnemonic generation options.
     * @returns A space-separated mnemonic string.
     */
    static fromEntropy(entropy, language, options = {}) {
        let raw;
        if (typeof entropy === 'string') {
            raw = hexToBytes(entropy);
        }
        else if (entropy instanceof Uint8Array) {
            raw = entropy;
        }
        else {
            raw = hexToBytes(entropy.getEntropy());
        }
        return this.encode(raw, language, options);
    }
    /**
     * Encode entropy into an Electrum-V1 mnemonic.
     *
     * @param entropy - Entropy as hex string or Uint8Array.
     * @param language - Language of the wordlist.
     * @param options - Optional mnemonic encoding options.
     * @throws {EntropyError} If entropy strength is invalid.
     * @returns A space-separated mnemonic string.
     */
    static encode(entropy, language, options = {}) {
        const entropyBytes = getBytes(entropy);
        if (!ElectrumV1Entropy.isValidBytesStrength(entropyBytes.length)) {
            throw new EntropyError('Wrong entropy strength', { expected: ElectrumV1Entropy.strengths, got: entropyBytes.length * 8 });
        }
        const rawList = this.getWordsListByLanguage(language, this.wordLists);
        const wordList = this.normalize(rawList);
        const wl = wordList.length;
        const mnemonic = [];
        for (let i = 0; i < entropyBytes.length; i += 4) {
            const chunkBytes = entropyBytes.slice(i, i + 4);
            // big-endian → bigint → number
            const chunkInt = Number(bytesToInteger(chunkBytes, false));
            const w1 = chunkInt % wl;
            const w2 = (Math.floor(chunkInt / wl) + w1) % wl;
            const w3 = (Math.floor(chunkInt / wl / wl) + w2) % wl;
            mnemonic.push(wordList[w1], wordList[w2], wordList[w3]);
        }
        return this.normalize(mnemonic).join(' ');
    }
    /**
     * Decode an Electrum-V1 mnemonic back to entropy.
     *
     * @param mnemonic - Mnemonic string or array of words.
     * @param options - Decoding options (e.g. checksum).
     * @throws {MnemonicError} If word count is invalid.
     * @returns Hex-encoded entropy string.
     */
    static decode(mnemonic, options = { checksum: false }) {
        const words = this.normalize(mnemonic);
        const count = words.length;
        if (!this.wordsList.includes(count)) {
            throw new MnemonicError('Invalid mnemonic words count', {
                expected: this.wordsList,
                got: count,
            });
        }
        let wordsList;
        let idxMap = {};
        if (options.wordsList && options.wordsListWithIndex) {
            wordsList = options.wordsList;
            idxMap = options.wordsListWithIndex;
        }
        else {
            [wordsList] = this.findLanguage(words, this.wordLists);
            wordsList.forEach((w, i) => (idxMap[w] = i));
        }
        const wl = wordsList.length;
        const bufs = [];
        for (let i = 0; i < words.length; i += 3) {
            const [w1, w2, w3] = words.slice(i, i + 3);
            const i1 = idxMap[w1];
            const i2 = idxMap[w2] % wl;
            const i3 = idxMap[w3] % wl;
            const chunkVal = i1 +
                wl * ((i2 - i1 + wl) % wl) +
                wl * wl * ((i3 - i2 + wl) % wl);
            const chunkBytes = integerToBytes(chunkVal, 4, 'big');
            bufs.push(getBytes(chunkBytes));
        }
        return bytesToHex(concatBytes(...bufs), false);
    }
    /**
     * Validate if the given input is a valid Electrum-V1 mnemonic.
     *
     * @param input - Mnemonic string or array of words.
     * @param options - Validation options.
     * @returns True if valid, false otherwise.
     */
    static isValid(input, options = {}) {
        try {
            this.decode(input, options);
            return true;
        }
        catch {
            return false;
        }
    }
    /**
     * Normalize input mnemonic or words list.
     *
     * @param input - Mnemonic string or array of words.
     * @returns Normalized array of lowercase words (NFKD).
     */
    static normalize(input) {
        const arr = typeof input === 'string' ? input.trim().split(/\s+/) : input;
        return arr.map(w => w.normalize('NFKD').toLowerCase());
    }
}
//# sourceMappingURL=mnemonic.js.map