import { Mnemonic } from '../../mnemonic';
import { Entropy } from '../../../entropies';
import { MnemonicOptionsInterface, ElectrumV1MnemonicLanguagesInterface, ElectrumV1MnemonicWordsInterface } from '../../../interfaces';
export declare const ELECTRUM_V1_MNEMONIC_WORDS: ElectrumV1MnemonicWordsInterface;
export declare const ELECTRUM_V1_MNEMONIC_LANGUAGES: ElectrumV1MnemonicLanguagesInterface;
/**
 * Electrum-V1 mnemonic implementation.
 *
 * Electrum-V1 mnemonics are generated by encoding entropy into
 * a sequence of words using the Electrum-V1 algorithm.
 */
export declare class ElectrumV1Mnemonic extends Mnemonic {
    static wordsListNumber: number;
    static wordsList: number[];
    static wordsToStrength: Record<number, number>;
    static languages: string[];
    static wordLists: Record<string, string[]>;
    /**
     * Get the name of this mnemonic type.
     *
     * @returns The string `"Electrum-V1"`.
     */
    static getName(): string;
    /**
     * Generate a mnemonic from word count and language.
     *
     * @param count - Number of words (must be in `wordsList`).
     * @param language - Language of the wordlist.
     * @param options - Optional mnemonic generation options.
     * @throws {MnemonicError} If the word count is invalid.
     * @returns A space-separated mnemonic string.
     */
    static fromWords(count: number, language: string, options?: MnemonicOptionsInterface): string;
    /**
     * Generate a mnemonic from entropy.
     *
     * @param entropy - Entropy in hex string, Uint8Array, or Entropy object form.
     * @param language - Language of the wordlist.
     * @param options - Optional mnemonic generation options.
     * @returns A space-separated mnemonic string.
     */
    static fromEntropy(entropy: string | Uint8Array | Entropy, language: string, options?: MnemonicOptionsInterface): string;
    /**
     * Encode entropy into an Electrum-V1 mnemonic.
     *
     * @param entropy - Entropy as hex string or Uint8Array.
     * @param language - Language of the wordlist.
     * @param options - Optional mnemonic encoding options.
     * @throws {EntropyError} If entropy strength is invalid.
     * @returns A space-separated mnemonic string.
     */
    static encode(entropy: string | Uint8Array, language: string, options?: MnemonicOptionsInterface): string;
    /**
     * Decode an Electrum-V1 mnemonic back to entropy.
     *
     * @param mnemonic - Mnemonic string or array of words.
     * @param options - Decoding options (e.g. checksum).
     * @throws {MnemonicError} If word count is invalid.
     * @returns Hex-encoded entropy string.
     */
    static decode(mnemonic: string | string[], options?: MnemonicOptionsInterface): string;
    /**
     * Validate if the given input is a valid Electrum-V1 mnemonic.
     *
     * @param input - Mnemonic string or array of words.
     * @param options - Validation options.
     * @returns True if valid, false otherwise.
     */
    static isValid(input: string | string[], options?: MnemonicOptionsInterface): boolean;
    /**
     * Normalize input mnemonic or words list.
     *
     * @param input - Mnemonic string or array of words.
     * @returns Normalized array of lowercase words (NFKD).
     */
    static normalize(input: string | string[]): string[];
}
//# sourceMappingURL=mnemonic.d.ts.map